### ISSUE TITLE
Update meta tags and favicons

### ISSUE THREAD

**Issue by mucahitnezir** [mucahitnezir/personal-website#4]
Review and update meta tags.

- [x] Set open graph meta tags
- [x] Set twitter meta tags
- [x] Set description meta tag
- [x] Set theme color meta tag
- [ ] Favicons (auto generate all sizes)
- [ ] Research and set manifest, if needed

**Comment by mucahitnezir** [comment]
To generate all sizes:

https://favicon.io/favicon-converter/
